spring:
  application:
    name: love-service
  datasource:
    dynamic:
      primary: love
      ## 开启 mybatis-plus 支持 很关键 ！！
      mpEnabled: true
      datasource:
        love:
          username: root
          password: '000000'
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/love?useAffectedRows=true
server:
  tomcat:
    accesslog:
      directory: /home/admin/love/logs
      enabled: true
  port: 18902

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.peer1:30000/eureka/,http://eureka.peer2:30000/eureka/
  instance:
    preferIpAddress: false
logging:
  config: classpath:logback-boot.xml

mybatis-plus:
  mapper-locations: classpath*:mapper/love/*Mapper.xml
  type-aliases-package: com.hbc.impl.model
