package com.hbc.impl.mapper;

import com.baomidou.dynamic.datasource.annotation.DS;

import com.hbc.impl.model.LoveMessage;
import com.hbc.impl.model.LoveMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@DS("love")
public interface LoveMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    long countByExample(LoveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int deleteByExample(LoveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int insert(LoveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int insertSelective(LoveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    List<LoveMessage> selectByExample(LoveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    LoveMessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LoveMessage record,
      @Param("example") LoveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LoveMessage record,
      @Param("example") LoveMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LoveMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table love_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoveMessage record);
}
